typography_spectrum: 0.7256112969480455
content_rating:
  adult: false
color:
  brandStrength: 0.6847391477786005
  lightness: 0.02863389952108264
  saturation: 0.3059508001897484
  rhythmicContrast: 0.08301537740044296
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  type: Website
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f874414-2010-4d66-b768-7b63afbf8093.png
layout_spectrum: 0.34596751048229635
author:
  name: ''
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a782cc1-977c-4bd3-a11b-7da62170c8e0.jpg
name: SAVID
navigation:
  - name: Display
    id: 56588c04-f600-4fad-a6b7-0e1f6e455abc
    type: content
  - name: Unified Collaboration System
    id: 964bb86b-817e-4c22-a0f6-8f27fe114060
    type: content
  - name: Networked AV Systems
    id: 81591792-843b-4c52-916e-7f88886a519f
    type: content
  - name: Audio Systems
    id: 25cbe1d5-1bdf-42cb-a442-b1bd278292f9
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/204856b0-081b-4b54-8301-edfc01911c60.ico
title: SAVID
description: The right solution within the budget
