typography_spectrum: 0.7256112969480455
content_rating:
  adult: false
color:
  brandStrength: 0.6847391477786005
  lightness: 0.02863389952108264
  saturation: 0.3059508001897484
  rhythmicContrast: 0.08301537740044296
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  type: Website
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2f874414-2010-4d66-b768-7b63afbf8093.png
layout_spectrum: 0.34596751048229635
author:
  name: Robin
  email: robin.tan@savid.asia
  url: www.savid.asia
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/61a00c03-1a92-4081-97d3-2b5a71ffff79.jpg
name: SAVID
navigation: []
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/204856b0-081b-4b54-8301-edfc01911c60.ico
title: The right solution within the budget
description: The right solution within the budget
